version: '3.7'
services:
 mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ECommerce
      MONGO_INITDB_URL: mongodb://localhost:27017/
volumes:
  pgdata: